"""
Global variables related to cyb3rhq-daemons
"""

LOGCOLLECTOR_DAEMON = 'cyb3rhq-logcollector'
AGENTLESS_DAEMON = 'cyb3rhq-agentlessd'
CSYSLOG_DAEMON = 'cyb3rhq-csyslogd'
REMOTE_DAEMON = 'cyb3rhq-remoted'
ANALYSISD_DAEMON = 'cyb3rhq-analysisd'
API_DAEMON = 'cyb3rhq-apid'
MAIL_DAEMON = 'cyb3rhq-maild'
SYSCHECK_DAEMON = 'cyb3rhq-syscheckd'
EXEC_DAEMON = 'cyb3rhq-execd'
MODULES_DAEMON = 'cyb3rhq-modulesd'
CLUSTER_DAEMON = 'cyb3rhq-clusterd'
INTEGRATOR_DAEMON = 'cyb3rhq-integratord'
MONITOR_DAEMON = 'cyb3rhq-monitord'
CYB3RHQ_DB_DAEMON = 'cyb3rhq-db'
AGENT_DAEMON = 'cyb3rhq-agentd'


CYB3RHQ_AGENT_DAEMONS = [LOGCOLLECTOR_DAEMON, SYSCHECK_DAEMON, EXEC_DAEMON, MODULES_DAEMON, AGENT_DAEMON]
CYB3RHQ_MANAGER_DAEMONS = [LOGCOLLECTOR_DAEMON, AGENTLESS_DAEMON, CSYSLOG_DAEMON, REMOTE_DAEMON, ANALYSISD_DAEMON,
                         API_DAEMON, MAIL_DAEMON, SYSCHECK_DAEMON, EXEC_DAEMON, MODULES_DAEMON, CLUSTER_DAEMON,
                         INTEGRATOR_DAEMON, MONITOR_DAEMON, CYB3RHQ_DB_DAEMON]

API_DAEMONS_REQUIREMENTS = [API_DAEMON, CYB3RHQ_DB_DAEMON, EXEC_DAEMON, ANALYSISD_DAEMON, REMOTE_DAEMON, MODULES_DAEMON]
